# Generated by Django 3.2.9 on 2024-04-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240430_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order',
            field=models.PositiveIntegerField(default=1, null=True, unique=True),
        ),
    ]
