# Generated by Django 3.2.9 on 2024-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240430_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
