# Generated by Django 3.2.9 on 2024-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freelance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='types',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
