# Generated by Django 3.2.9 on 2024-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240502_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
